name:                ScratchLens
version:             0.1.0.0
github:              "jeorp/ScratchLens"
license:             BSD3
author:              "jeorp"
maintainer:          "jeorpqxx@gmail.com"
copyright:           "2021 jeorp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeorp/ScratchLens#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- profunctors
- tagged
- random
- data-default-class
- hspec

library:
  source-dirs: src

executables:
  ScratchLens-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScratchLens

tests:
  ScratchLens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScratchLens
